name: track_luanti

# build on c/cpp changes or workflow changes
on:
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'
  push:
    branches:
      - master
# IMPORTANT: Do not run this workflow on pull request since this workflow
# has permission to modify contents.

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  # Current gcc version
  update_repo:
    runs-on: ubuntu-22.04
    steps:
      # Check out this repo
      - uses: actions/checkout@v4
      - name: Update Luanti revision
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          ./update-revs.sh  # sets LUANTI_REV
          ./push-revs.sh    # sets DID_PUSH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Checkout Luanti
      - uses: actions/checkout@v4
        if: ${{ env.DID_PUSH == 'true' }}
        with:
          repository: '${{ github.repository_owner }}/luanti'
          ref: ${{ env.LUANTI_REV }}
          path: 'luanti'
      - name: Install deps
        if: ${{ env.DID_PUSH == 'true' }}
        run: |
          pushd luanti
          source ./util/ci/common.sh
          install_linux_deps g++-12
          popd
      - name: Build
        if: ${{ env.DID_PUSH == 'true' }}
        run: |
          pushd luanti
          ./util/ci/build.sh
          popd
        env:
          CC: gcc-12
          CXX: g++-12
          CMAKE_BUILD_TYPE: "Release"
          CMAKE_BUILD_SERVER: FALSE
          CMAKE_ENABLE_GETTEXT: FALSE
          # Do not build tests: Tests may add spam to the benchmark output, letting parsing fail.
          CMAKE_FLAGS: "-DBUILD_BENCHMARKS=TRUE -DBUILD_UNITTESTS=FALSE"
      - name: Run Benchmarks
        if: ${{ env.DID_PUSH == 'true' }}
        run: |
          pushd luanti
          ./bin/luanti --run-benchmarks 2>../output.txt
          cat ../output.txt
          popd
      # gh-pages branch is updated and pushed automatically with extracted benchmark data
      - name: Store benchmark result
        if: ${{ env.DID_PUSH == 'true' }}
        uses: benchmark-action/github-action-benchmark@v1.20.4
        with:
          name: Luanti Performance Benchmarks
          tool: 'catch2'
          output-file-path: output.txt
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          # If there's a regression, comment on the commit.
          # Temporarily disabled due to a bug in github-action-benchmark
          comment-on-alert: false
          # Branch and path where benchmark is stored and updated.
          # This corresponds to:
          #     https://www.luanti.org/benchmarks/dev/bench/
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "dev/bench"
